// browser/src/components/SendTab.vue
<script setup lang="ts">
import { ref } from "vue";
import { Button } from "./ui/button";
import { Upload, Link as LinkIcon, Check } from "lucide-vue-next";
import { sendFile } from "@/lib/commands";

const file = ref<File | null>(null);
const ticket = ref<string>("");
const isSending = ref(false);
const isDragging = ref(false);
const fileInput = ref<HTMLInputElement | null>(null);

async function handleSend() {
  if (!file.value) return;

  isSending.value = true;
  try {
    ticket.value = await sendFile(file.value);
  } catch (error) {
    console.error("Send failed:", error);
    alert("Failed to send file: " + (error as Error).message);
  } finally {
    isSending.value = false;
  }
}

function handleFileSelect(event: Event) {
  const target = event.target as HTMLInputElement;
  if (target.files && target.files[0]) {
    file.value = target.files[0];
    ticket.value = "";
  }
}

function handleDrop(event: DragEvent) {
  event.preventDefault();
  isDragging.value = false;
  if (event.dataTransfer?.files && event.dataTransfer.files[0]) {
    file.value = event.dataTransfer.files[0];
    ticket.value = "";
  }
}

function handleDragOver(event: DragEvent) {
  event.preventDefault();
  isDragging.value = true;
}

function handleDragLeave() {
  isDragging.value = false;
}

function copyTicket() {
  navigator.clipboard.writeText(ticket.value);
}

function selectFile() {
  fileInput.value?.click();
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return bytes + " B";
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + " KB";
  return (bytes / (1024 * 1024)).toFixed(1) + " MB";
}
</script>

<template>
  <div class="space-y-6">
    <div class="text-center">
      <h2 class="text-2xl font-bold text-white mb-2">Send Files</h2>
      <p class="text-white/60">Share files securely over P2P</p>
    </div>

    <div
      class="border-2 border-dashed rounded-xl p-8 text-center transition-colors cursor-pointer"
      :class="
        isDragging
          ? 'border-purple-400 bg-purple-500/10'
          : 'border-white/20 bg-white/5 hover:border-white/30 hover:bg-white/10'
      "
      @drop="handleDrop"
      @dragover="handleDragOver"
      @dragleave="handleDragLeave"
      @click="selectFile"
    >
      <input
        ref="fileInput"
        type="file"
        class="hidden"
        @change="handleFileSelect"
      />

      <Upload v-if="!file" :size="48" class="mx-auto mb-4 text-white/40" />

      <Check v-else :size="48" class="mx-auto mb-4 text-green-400" />

      <div v-if="!file" class="text-white/80">
        Drop a file here or click to browse
      </div>
      <div v-else class="text-white">
        <div class="font-medium truncate">{{ file.name }}</div>
        <div class="text-sm text-white/60 mt-1">
          {{ formatFileSize(file.size) }}
        </div>
      </div>

      <input
        ref="fileInput"
        type="file"
        class="hidden"
        @change="handleFileSelect"
      />
    </div>

    <Button
      v-if="file && !ticket"
      size="lg"
      class="w-full h-12 text-base"
      :disabled="isSending"
      @click="handleSend"
    >
      {{ isSending ? "Creating Ticket..." : "Create Ticket" }}
    </Button>

    <div
      v-if="ticket"
      class="rounded-xl bg-white/5 border border-white/10 p-6 space-y-4"
    >
      <div class="flex items-center gap-2 text-green-400">
        <Check :size="20" />
        <span class="font-medium">Ready to Share</span>
      </div>

      <div>
        <label class="text-sm text-white/60 mb-2 block">Share Ticket</label>
        <div class="flex gap-2">
          <input
            :value="ticket"
            readonly
            class="flex-1 bg-black/30 border border-white/10 rounded-lg px-4 py-3 text-white text-sm font-mono"
          />
          <Button variant="outline" size="icon" @click="copyTicket">
            <LinkIcon :size="18" />
          </Button>
        </div>
      </div>

      <p class="text-sm text-white/50">
        Share this ticket with the recipient. They can use it to download your
        file.
      </p>
    </div>
  </div>
</template>

// browser/src/components/sendme/SendTab.tsx
import { createSignal, createMemo, Show } from "solid-js";
import toast from "solid-toast";
import { sendFile } from "../../lib/commands";
import { Motion, Presence } from "solid-motionone";
import {
  TbOutlineUpload,
  TbOutlineCheck,
  TbOutlineCopy,
  TbOutlineFileText,
  TbOutlineX,
  TbOutlineSparkles,
  TbOutlineDevices,
} from "solid-icons/tb";
import DeviceListModal from "../devices/DeviceListModal";

interface Device {
  id: string;
  userId: string;
  platform: string;
  deviceId: string;
  name: string;
  ipAddress: string | null;
  hostname: string | null;
  userAgent: string | null;
  online: boolean;
  lastSeenAt: string;
  createdAt: string;
  updatedAt: string;
}

interface SendTabProps { }

export default function SendTab(_props: SendTabProps) {
  const [file, setFile] = createSignal<File | null>(null);
  const [ticket, setTicket] = createSignal<string>("");
  const [isSending, setIsSending] = createSignal(false);
  const [isDragging, setIsDragging] = createSignal(false);
  const [isDeviceModalOpen, setIsDeviceModalOpen] = createSignal(false);
  let fileInputRef: HTMLInputElement | undefined;

  const dropZoneClass = createMemo(() =>
    isDragging()
      ? "border-purple-500/50 bg-purple-500/10 scale-[1.02]"
      : file()
        ? "border-green-500/30 bg-green-500/5"
        : "border-white/10 bg-white/5 hover:border-white/20 hover:bg-white/10"
  );

  async function handleSend() {
    const currentFile = file();
    if (!currentFile) return;

    setIsSending(true);
    try {
      const result = await sendFile(currentFile);
      setTicket(result);
      toast.success("Ticket ready to share!");
    } catch (error) {
      console.error("Send failed:", error);
      toast.error("Failed to share file: " + (error as Error).message);
    } finally {
      setIsSending(false);
    }
  }

  function handleFileSelect(event: Event) {
    const target = event.target as HTMLInputElement;
    if (target.files && target.files[0]) {
      setFile(target.files[0]);
      setTicket("");
    }
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault();
    setIsDragging(false);
    if (event.dataTransfer?.files && event.dataTransfer.files[0]) {
      setFile(event.dataTransfer.files[0]);
      setTicket("");
    }
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
    setIsDragging(true);
  }

  function handleDragLeave() {
    setIsDragging(false);
  }

  function copyTicket() {
    navigator.clipboard.writeText(ticket());
    toast.success("Copied to clipboard!");
  }

  function selectFile() {
    fileInputRef?.click();
  }

  function resetFile() {
    setFile(null);
    setTicket("");
  }

  function formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + " B";
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + " KB";
    return (bytes / (1024 * 1024)).toFixed(1) + " MB";
  }

  /**
   * Handle sending ticket to a device
   */
  async function handleSendToDevice(device: Device) {
    try {
      const currentFile = file();
      const response = await fetch("/api/tickets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          deviceId: device.deviceId,
          ticket: ticket(),
          filename: currentFile?.name,
          fileSize: currentFile?.size,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to send ticket");
      }

      toast.success(`Ticket sent to ${device.name}!`);
      setIsDeviceModalOpen(false);
    } catch (error) {
      console.error("Failed to send ticket:", error);
      toast.error("Failed to send ticket: " + (error as Error).message);
    }
  }

  return (
    <div class="space-y-8">
      {/* Header Info */}
      <div class="text-center space-y-2">
        <h2 class="text-2xl font-bold bg-clip-text text-transparent bg-linear-to-r from-white to-white/70">
          Share a File
        </h2>
        <p class="text-white/40 text-sm">
          Everything is encrypted and sent directly peer-to-peer.
        </p>
      </div>

      {/* Main Action Area */}
      <div class="relative group">
        <Presence exitBeforeEnter>
          <Show
            when={!file()}
            fallback={
              <Motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 1.1 }}
                transition={{ duration: 0.2 }}
                class={`relative border-2 border-dashed rounded-3xl p-10 text-center transition-all duration-300 overflow-hidden ${dropZoneClass()}`}
              >
                <div class="flex flex-col items-center gap-4 py-2">
                  <Motion.div
                    initial={{ scale: 0.8 }}
                    animate={{ scale: 1 }}
                    class="w-16 h-16 rounded-2xl bg-green-500/20 text-green-400 flex items-center justify-center relative"
                  >
                    <TbOutlineFileText size={32} />
                    <button
                      onClick={(e) => { e.stopPropagation(); resetFile(); }}
                      class="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-white/10 hover:bg-white/20 text-white/60 flex items-center justify-center backdrop-blur-md border border-white/10"
                    >
                      <TbOutlineX size={12} />
                    </button>
                  </Motion.div>
                  <div class="max-w-xs">
                    <p class="font-semibold text-white truncate px-4">{file()!.name}</p>
                    <p class="text-xs text-white/40 mt-1">{formatFileSize(file()!.size)}</p>
                  </div>
                </div>
              </Motion.div>
            }
          >
            <Motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              class={`relative border-2 border-dashed rounded-3xl p-10 text-center transition-all duration-300 cursor-pointer overflow-hidden ${dropZoneClass()}`}
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onClick={selectFile}
            >
              <input
                ref={fileInputRef}
                type="file"
                class="hidden"
                onChange={handleFileSelect}
              />
              <div class="flex flex-col items-center gap-5 py-4">
                <div class="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center group-hover:bg-purple-500/20 group-hover:text-purple-400 transition-all duration-500">
                  <TbOutlineUpload size={32} class="opacity-50 group-hover:opacity-100" />
                </div>
                <div>
                  <p class="text-white/80 font-medium mb-1">Click to browse or drop file</p>
                  <p class="text-white/40 text-sm">Maximum file size: 1GB</p>
                </div>
              </div>
            </Motion.div>
          </Show>
        </Presence>
      </div>

      {/* Action Button */}
      <Show when={file() && !ticket()}>
        <Motion.button
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          hover={{ scale: 1.02 }}
          press={{ scale: 0.98 }}
          onClick={handleSend}
          disabled={isSending()}
          class="w-full py-4 px-6 bg-linear-to-r from-purple-500 via-indigo-500 to-purple-600 hover:hue-rotate-15 disabled:grayscale text-white rounded-2xl font-bold transition-all shadow-xl shadow-purple-500/20 disabled:cursor-not-allowed flex items-center justify-center gap-3 relative overflow-hidden"
        >
          <Show when={isSending()}>
            <div class="absolute inset-0 shimmer opacity-20" />
            <div class="w-5 h-5 border-3 border-white/20 border-t-white rounded-full animate-spin" />
            <span>Encapsulating...</span>
          </Show>
          <Show when={!isSending()}>
            <TbOutlineSparkles size={20} class="animate-float" />
            <span>Generate Shared Ticket</span>
          </Show>
        </Motion.button>
      </Show>

      {/* Result Display */}
      <Presence>
        <Show when={ticket()}>
          <Motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            class="glass rounded-3xl p-6 border-indigo-500/20 bg-indigo-500/5 space-y-5"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <div class="w-8 h-8 rounded-full bg-green-500/20 text-green-400 flex items-center justify-center">
                  <TbOutlineCheck size={18} />
                </div>
                <span class="font-bold text-white">Target Locked</span>
              </div>
              <span class="text-[10px] font-black uppercase tracking-widest text-white/20">Ticket Type: P2P</span>
            </div>

            <div class="space-y-3">
              <div class="flex gap-2">
                <div class="flex-1 bg-black/40 border border-white/10 rounded-2xl px-5 py-4 text-white text-sm font-mono break-all line-clamp-2">
                  {ticket()}
                </div>
                <button
                  onClick={copyTicket}
                  class="p-4 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl transition-all group active:scale-90"
                  title="Copy ticket"
                >
                  <TbOutlineCopy size={24} class="text-white/60 group-hover:text-white" />
                </button>
                <button
                  onClick={() => setIsDeviceModalOpen(true)}
                  class="p-4 bg-purple-500/10 hover:bg-purple-500/20 border border-purple-500/30 rounded-2xl transition-all group active:scale-90"
                  title="Send to your device"
                >
                  <TbOutlineDevices size={24} class="text-purple-400 group-hover:text-purple-300" />
                </button>
              </div>
              <p class="text-xs text-white/30 text-center">
                Send this secret ticket to someone to authorize download.
              </p>
            </div>
          </Motion.div>
        </Show>
      </Presence>

      {/* Device List Modal */}
      <DeviceListModal
        isOpen={isDeviceModalOpen()}
        onClose={() => setIsDeviceModalOpen(false)}
        ticket={ticket()}
        showSendButton={true}
        onSendToDevice={handleSendToDevice}
      />
    </div>
  );
}
