// browser/src/components/sendme/ReceiveTab.tsx
import { createSignal, Show, For } from "solid-js";
import toast from "solid-toast";
import { receiveFile, downloadFile } from "../../lib/commands";
import {
  TbOutlineDownload,
  TbOutlineCheck,
  TbOutlineAlertCircle,
  TbOutlineClipboard,
  TbOutlineShieldLock,
  TbOutlineSparkles,
  TbOutlineDeviceMobile,
  TbOutlineFile,
  TbOutlinePhoto,
  TbOutlineVideo,
} from "solid-icons/tb";
import { useTicketPolling } from "~/lib/composables/useTicketPolling";

function getMimeType(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() || "";
  const mimeTypes: Record<string, string> = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    gif: "image/gif",
    webp: "image/webp",
    mp4: "video/mp4",
    webm: "video/webm",
    pdf: "application/pdf",
    txt: "text/plain",
  };
  return mimeTypes[ext] || "application/octet-stream";
}

function isPreviewable(filename: string): boolean {
  const mime = getMimeType(filename);
  return mime.startsWith("image/") || mime.startsWith("video/");
}

function createPreviewUrl(data: Uint8Array, filename: string): string {
  const mime = getMimeType(filename);
  const blob = new Blob([data], { type: mime });
  return URL.createObjectURL(blob);
}

export default function ReceiveTab(props: { isActive?: boolean }) {
  const [ticket, setTicket] = createSignal<string>("");
  const [isReceiving, setIsReceiving] = createSignal(false);
  const [receivedFile, setReceivedFile] = createSignal<{
    filename: string;
    data: Uint8Array;
  } | null>(null);
  const [error, setError] = createSignal<string>("");

  const { tickets } = useTicketPolling(() => props.isActive || false);

  async function handleReceive() {
    const ticketValue = ticket().trim();
    if (!ticketValue) {
      toast.error("Please enter a ticket");
      return;
    }

    setIsReceiving(true);
    setError("");
    setReceivedFile(null);

    try {
      const result = await receiveFile(ticketValue);
      setReceivedFile(result);
      toast.success("File received successfully!");
    } catch (err) {
      const errorMsg = (err as Error).message || "Failed to receive file";
      setError(errorMsg);
      toast.error(errorMsg);
    } finally {
      setIsReceiving(false);
    }
  }

  function downloadReceivedFile() {
    const file = receivedFile();
    if (!file) return;
    downloadFile(file.data, file.filename);
    toast.success(`Downloaded ${file.filename}`);
  }

  async function pasteTicket() {
    try {
      const text = await navigator.clipboard.readText();
      setTicket(text);
      toast.success("Ticket pasted!");
    } catch (err) {
      toast.error("Failed to read clipboard.");
    }
  }

  function useIncomingTicket(ticketStr: string, filename?: string | null) {
    setTicket(ticketStr);
    toast.success(`Ticket from ${filename || "another device"} loaded!`);
  }

  function formatFileSize(data: Uint8Array): string {
    if (!data || typeof data.length !== "number") return "Unknown size";
    const size = data.length;
    if (size < 1024) return size + " B";
    if (size < 1024 * 1024) return (size / 1024).toFixed(1) + " KB";
    return (size / (1024 * 1024)).toFixed(1) + " MB";
  }

  return (
    <div class="space-y-6">
      {/* Header */}
      <div class="text-center">
        <h2 class="text-2xl font-bold">Receive a File</h2>
        <p class="text-base-content/60 text-sm mt-1">
          Enter a secure ticket to establish a P2P connection.
        </p>
      </div>

      {/* Incoming Tickets */}
      <Show when={tickets().length > 0}>
        <div class="alert alert-warning">
          <TbOutlineSparkles size={18} />
          <div class="flex-1">
            <span class="font-semibold">
              {tickets().length} Incoming Ticket
              {tickets().length > 1 ? "s" : ""}
            </span>
          </div>
        </div>
        <div class="space-y-2 max-h-40 overflow-y-auto">
          <For each={tickets()}>
            {(incomingTicket) => (
              <div
                class="flex items-center gap-3 p-3 rounded-xl bg-base-300/50 hover:bg-base-300 cursor-pointer transition-colors"
                onClick={() =>
                  useIncomingTicket(
                    incomingTicket.ticket,
                    incomingTicket.filename,
                  )
                }
              >
                <div class="w-8 h-8 rounded-lg bg-primary/20 text-primary flex items-center justify-center">
                  <TbOutlineDeviceMobile size={16} />
                </div>
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-medium truncate">
                    {incomingTicket.filename || "Unnamed file"}
                  </p>
                  <p class="text-xs text-base-content/50">
                    {incomingTicket.fileSize
                      ? `${(incomingTicket.fileSize / 1024 / 1024).toFixed(2)} MB`
                      : "Unknown size"}
                  </p>
                </div>
                <TbOutlineCheck
                  size={16}
                  class="text-primary opacity-0 group-hover:opacity-100"
                />
              </div>
            )}
          </For>
        </div>
      </Show>

      {/* Ticket Input */}
      <div class="form-control">
        <label class="input input-bordered flex items-center gap-2 w-full">
          <TbOutlineShieldLock size={18} class="opacity-50" />
          <input
            type="text"
            value={ticket()}
            onInput={(e) => setTicket(e.currentTarget.value)}
            placeholder="Enter or paste ticket code..."
            class="grow font-mono text-sm"
            disabled={isReceiving()}
          />
          <button
            onClick={pasteTicket}
            class="btn btn-ghost btn-sm"
            disabled={isReceiving()}
            title="Paste from clipboard"
          >
            <TbOutlineClipboard size={16} />
          </button>
        </label>
      </div>

      <button
        onClick={handleReceive}
        disabled={!ticket().trim() || isReceiving()}
        class={`btn btn-primary btn-block ${isReceiving() ? "loading" : ""}`}
      >
        <Show when={!isReceiving()}>
          <TbOutlineDownload size={18} /> Retrieve File
        </Show>
      </button>

      {/* Error Alert */}
      <Show when={error()}>
        <div class="alert alert-error">
          <TbOutlineAlertCircle size={18} />
          <span>{error()}</span>
        </div>
      </Show>

      {/* Success - File Ready */}
      <Show when={receivedFile()}>
        <div class="alert alert-success">
          <TbOutlineCheck size={18} />
          <div class="flex-1">
            <p class="font-bold">File Available</p>
            <p class="text-sm font-mono truncate">{receivedFile()!.filename}</p>
            <p class="text-xs opacity-60">
              {formatFileSize(receivedFile()!.data)} • Ready to download
            </p>
          </div>
        </div>

        <Show when={isPreviewable(receivedFile()!.filename)}>
          <div class="w-full h-48 rounded-2xl overflow-hidden bg-base-300">
            <img
              src={createPreviewUrl(
                receivedFile()!.data,
                receivedFile()!.filename,
              )}
              alt={receivedFile()!.filename}
              class="w-full h-full object-contain"
            />
          </div>
        </Show>

        <button
          onClick={downloadReceivedFile}
          class="btn btn-success btn-block"
        >
          <TbOutlineDownload size={18} /> Save to Device
        </button>
      </Show>
    </div>
  );
}

// browser/src/components/ReceiveTab.vue
<script setup lang="ts">
import { ref } from "vue";
import { Button } from "./ui/button";
import { Download, Check, AlertCircle } from "lucide-vue-next";
import { receiveFile, downloadFile } from "@/lib/commands";

const ticket = ref<string>("");
const isReceiving = ref(false);
const receivedFile = ref<{ filename: string; data: Uint8Array } | null>(null);
const error = ref<string>("");

async function handleReceive() {
  if (!ticket.value.trim()) return;

  isReceiving.value = true;
  error.value = "";
  receivedFile.value = null;

  try {
    const result = await receiveFile(ticket.value.trim());
    receivedFile.value = result;
  } catch (err) {
    error.value = (err as Error).message || "Failed to receive file";
  } finally {
    isReceiving.value = false;
  }
}

function downloadReceivedFile() {
  if (!receivedFile.value) return;
  downloadFile(receivedFile.value.data, receivedFile.value.filename);
}

function pasteTicket() {
  navigator.clipboard.readText().then((text) => {
    ticket.value = text;
  });
}

function formatFileSize(bytes: Uint8Array): string {
  const size = bytes.length;
  if (size < 1024) return size + " B";
  if (size < 1024 * 1024) return (size / 1024).toFixed(1) + " KB";
  return (size / (1024 * 1024)).toFixed(1) + " MB";
}
</script>

<template>
  <div class="space-y-6">
    <div class="text-center">
      <h2 class="text-2xl font-bold text-white mb-2">Receive Files</h2>
      <p class="text-white/60">Enter a ticket to download files</p>
    </div>

    <div class="space-y-4">
      <div>
        <label class="text-sm text-white/80 mb-2 block">Ticket</label>
        <div class="flex gap-2">
          <input
            v-model="ticket"
            type="text"
            placeholder="Paste ticket here..."
            class="flex-1 bg-black/30 border border-white/10 rounded-lg px-2 py-2 text-white placeholder:text-white/40 focus:outline-none focus:border-purple-400"
            :disabled="isReceiving"
          />
          <Button
            variant="outline"
            class="shrink-0 min-w-10"
            size="icon"
            @click="pasteTicket"
          >
            📋
          </Button>
        </div>
      </div>

      <Button
        size="lg"
        class="w-full h-12 text-base"
        :disabled="!ticket.trim() || isReceiving"
        @click="handleReceive"
      >
        <Download v-if="!isReceiving" :size="20" class="mr-2" />
        {{ isReceiving ? "Connecting..." : "Download File" }}
      </Button>
    </div>

    <div
      v-if="error"
      class="rounded-xl bg-red-500/10 border border-red-500/20 p-6"
    >
      <div class="flex items-center gap-2 text-red-400 mb-2">
        <AlertCircle :size="20" />
        <span class="font-medium">Error</span>
      </div>
      <p class="text-white/70 text-sm">{{ error }}</p>
    </div>

    <div
      v-if="receivedFile"
      class="rounded-xl bg-white/5 border border-white/10 p-6 space-y-4"
    >
      <div class="flex items-center gap-2 text-green-400">
        <Check :size="20" />
        <span class="font-medium">File Received</span>
      </div>

      <div class="bg-black/30 rounded-lg p-4">
        <div class="font-medium text-white truncate">
          {{ receivedFile.filename }}
        </div>
        <div class="text-sm text-white/60 mt-1">
          {{ formatFileSize(receivedFile.data) }}
        </div>
      </div>

      <Button size="lg" class="w-full" @click="downloadReceivedFile">
        <Download :size="20" class="mr-2" />
        Save to Device
      </Button>
    </div>
  </div>
</template>
